apiVersion: v1
kind: Service
metadata:
  name: nodeapp-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    nodeapp: web
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001